import { Component } from '@angular/core';

@Component({
  selector: 'app-usertable',
  templateUrl: './usertable.component.html',
  styleUrls: ['./usertable.component.css'],
})
export class UsertableComponent {
  tab: string = 'user';

  setTab(tab: string) {
    this.tab = tab;
    console.log(this.tab);
  }

  innerTab: string = 'active';

  setInnerTab(innerTab: string) {
    this.innerTab = innerTab;
    console.log('innerTab::', this.innerTab);
  }

  user: any[] = [
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
    {
      id: 1,
      lastname: 'lastname',
      firstname: 'fname',
      territory: 'tr',
      desk: 'desk',
      profile: 'prf',
      uid: 'uid',
      status: 'single',
      trigram: 'no idea',
      location: 'hunik',
    },
  ];
}
